version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  airflow-init:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}  # From .env

    command: db init
  airflow-webserver:
    build: .
    volumes:
      - ./src/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./requirements.txt:/requirements.txt
      - ./data:/opt/airflow/data  # Mounts root/data for CSV access
    restart: always
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}  # From .env
      AIRFLOW__CORE__TEST_CONNECTION: Enabled  # Enables Test button
      PYTHONWARNINGS: ignore::SyntaxWarning  # Suppress log clutter
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}  # From .env
      KAGGLE_KEY: ${KAGGLE_KEY}  # From .env
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}  # From .env
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}  # From .env
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"
    command: webserver
  airflow-scheduler:
    build: .
    volumes:
      - ./src/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./requirements.txt:/requirements.txt
      - ./data:/opt/airflow/data  # Mounts root/data for CSV access
    restart: always
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}  # From .env
      AIRFLOW__CORE__TEST_CONNECTION: Enabled  # Enables Test button
      PYTHONWARNINGS: ignore::SyntaxWarning  # Suppress log clutter
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}  # From .env
      KAGGLE_KEY: ${KAGGLE_KEY}  # From .env
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}  # From .env
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}  # From .env
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: scheduler